## Environment name. Set per environment (production | development)
# enviroment: ''
service:
  ## Service name. Service name MUST be specified by each service
  name: 'shipping'

secrets:
  enabled: true
  env:
    - name: AUTHENTICATION_SECRET
      valueFrom:
      secretKeyRef:
        name: auth
        key: authentication-secret
    - name: QUEUE_URL
      valueFrom:
      secretKeyRef:
        name: queue
        key: url
    - name: REDIS_URL
      valueFrom:
      secretKeyRef:
        name: redis
        key: url
    - name: TYPEORM_DATABASE
      valueFrom:  
      secretKeyRef:
        name: database
        key: database
    - name: TYPEORM_HOST
      valueFrom:
      secretKeyRef:
        name: database
        key: hostname
    - name: TYPEORM_PASSWORD
      valueFrom:
      secretKeyRef:
        name: database
        key: password
    - name: TYPEORM_PORT
      valueFrom:
      secretKeyRef:
        name: database
        key: port
    - name: TYPEORM_USERNAME
      valueFrom:
      secretKeyRef:
        name: database
        key: username

